### ISSUE TITLE
Failure to build a rails application.

### ISSUE THREAD

**Issue by andreas-kupries** [paketo-buildpacks/full-builder#818]
Issue context is https://github.com/epinio/epinio/issues/1857

As part of our CI we are building the ruby application https://github.com/epinio/example-rails with the latest `full` paketobuilder.
Starting last Friday the CI fails to build the application.
As the application sources have not changed since March this year I looked at the builder instead.

Using a throwaway PR ( https://github.com/epinio/epinio/pull/1860 ) I have bisected the issue to the transition from `0.2.222-full` to `0.2.223-full`. Relevant logs are attached, see `Steps To Repro` below.

## Expected Behavior

For the application to be build successfully by paketo

## Current Behavior

Building the application fails somewhere in the paketo builder.
Excerpt from the log for the failure case. This is around line 390:

```
       Compiling... 
       Compilation failed: 
       Browserslist: caniuse-lite is outdated. Please run: 
       npx browserslist@latest --update-db 
  
       Why you should do it regularly: 
       https://github.com/browserslist/browserslist#browsers-data-updating 
       node:internal/crypto/hash:71 
         this[kHandle] = new _Hash(algorithm, xofLen); 
                         ^ 
  
       Error: error:0308010C:digital envelope routines::unsupported 
           at new Hash (node:internal/crypto/hash:71:19) 
           at Object.createHash (node:crypto:133:10) 
           at module.exports (/layers/paketo-buildpacks_yarn-install/build-modules/node_modules/webpack/lib/util/createHash.js:135:53) 
           at NormalModule._initBuildHash (/layers/paketo-buildpacks_yarn-install/build-modules/node_modules/webpack/lib/NormalModule.js:417:16) 
           at /layers/paketo-buildpacks_yarn-install/build-modules/node_modules/webpack/lib/NormalModule.js:452:10 
           at /layers/paketo-buildpacks_yarn-install/build-modules/node_modules/webpack/lib/NormalModule.js:323:13 
           at /layers/paketo-buildpacks_yarn-install/build-modules/node_modules/loader-runner/lib/LoaderRunner.js:367:11 
           at /layers/paketo-buildpacks_yarn-install/build-modules/node_modules/loader-runner/lib/LoaderRunner.js:233:18 
           at context.callback (/layers/paketo-buildpacks_yarn-install/build-modules/node_modules/loader-runner/lib/LoaderRunner.js:111:13) 
           at /layers/paketo-buildpacks_yarn-install/build-modules/node_modules/babel-loader/lib/index.js:59:103 { 
         opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ], 
         library: 'digital envelope routines', 
         reason: 'unsupported', 
         code: 'ERR_OSSL_EVP_UNSUPPORTED' 
       } 

```

## Possible Solution

I cannot propose a solution because I am currently not able to distinguish if I am looking at

  - An incompatible change in the builder the ruby application should be adapted to, or
  - An issue slipped into the builder which is exposed by this specific application and needs attention and fixing in paketo.

While I see a number of packages getting version bumps in the log delta from 222 to 223 I am unable to say which of these might be the origin of the problem, if at all.

## Steps to Reproduce

Attached are the builder logs for the good and failing builds
 - [222-good-plain.txt](https://github.com/paketo-buildpacks/full-builder/files/10032996/222-good-plain.txt)
 - [223-bad-plain.txt](https://github.com/paketo-buildpacks/full-builder/files/10032997/223-bad-plain.txt)

I removed the output from our CI (github action + ginkgo) before and after paketo output, as well as the prefixes for each line which they added. To reduce the amount of (likely) irrelevant deltas I also sorted the lines emitted by the `bundle install` (74-220) into lexicographic order.

## Motivations

We would like our CI to be happy.

**Comment by fg-j** [comment]
Looking at [the diff between those builder releases](https://github.com/paketo-buildpacks/full-builder/compare/v0.2.222...v0.2.223) I see that the minor version of the ruby buildpack was upgraded. [Comparing those ruby buildpack releases](https://github.com/paketo-buildpacks/ruby/compare/v0.17.0...v0.18.0), I see that [the node-engine buildpack was upgraded](https://github.com/paketo-buildpacks/ruby/compare/v0.17.0...v0.18.0#diff-5f54cb49d0e28117084fad482c0daf89502d4ecb329230071fcf78e56dc939b3L39) to version 0.19.0. That upgrade changed the default version of node that is supplied by the buildpack [from 16 to 18](https://github.com/paketo-buildpacks/node-engine/compare/v0.18.0...v0.19.0#diff-5f54cb49d0e28117084fad482c0daf89502d4ecb329230071fcf78e56dc939b3L17). I think that's the root of your issue. @paketo-buildpacks/nodejs-maintainers I think you've seen this before. What are the mitigations?

**Comment by ryanmoran** [comment]
You can update `webpack` by updating the `webpacker` gem in your `Gemfile` to `6.0.0.rc.6`. Other instructions for this update can be found in their docs: https://github.com/rails/webpacker/blob/master/docs/v6_upgrade.md

**Comment by andreas-kupries** [comment]
Thank you for all the responses. 

@sophiewigmore 's plan (A) looks to be the simplest to implement, I will start with trying that.

**Comment by andreas-kupries** [comment]
Plan A worked out for me. Closing this issue now, with thanks for the help.
